services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env # 加载环境变量
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./data/certbot/conf:/etc/letsencrypt:ro
      - ./data/certbot/www:/var/www/certbot:ro
      - ${NAVYDEV_TOP_ROOT}:/usr/share/nginx/html/navydev.top:ro
      - ${CRABTRIS_NAVYDEV_TOP_ROOT}:/usr/share/nginx/html/crabtris.navydev.top:ro
      - ${RSS_NAVYDEV_TOP_ROOT}/dist:/usr/share/nginx/html/rss.navydev.top:ro
    restart: always
    networks:
      - otel-net

networks:
  otel-net:
    driver: bridge
    external: true
